- db/migrate/20221006214942_add_completed_notes_feedback_rating_to_user_challenges.rb
- db/schema.rb
Fixed typo as I couldn't migrate. changed interger to integer.
> Fix migration typo

- app/views/pages/home.html.erb
feat: added details regarding mentor pathway.
feat: added details regarding become a mentor.
feat: added details regarding find a mentor.
feat: changed pictures for mentor pathway section.
feat: changed pictures for find mentor section.
fix: bundle install as local host was not loading page properly.
fix: ./bin/dev had to use this command in terminal instead of rails s to load local host properly.
> filled in information

- app/models/challenge.rb
- config/routes.rb
- db/seeds.rb
feat: created validation for challenges, which include title and details.
test: added code in seed file so i can test adding a user and creating a challenge.
> challenge validations completed [MP-27]

- Gemfile.lock
- app/models/user.rb
- config/initializers/devise.rb
- db/migrate/20221026203006_add_first_name_to_users.rb
- db/migrate/20221026203021_add_last_name_to_users.rb
- db/migrate/20221026205729_add_role_to_users.rb
- db/schema.rb
Added first, last name and role attributes to devise user model.
First, last name added as strings.
Role attribute added as enum, which gives option to add additional user classes in future.
> User migrations

- Gemfile
- Gemfile.lock
- app/models/challenge.rb
- app/models/pathway.rb
- app/models/user.rb
also removed unnecessary commas from some validations
> fix: remove comma from user model that resulted in unexpected end [MP-32]

- Gemfile
- Gemfile.lock
- app/models/challenge.rb
- app/models/path_challenge.rb
- app/models/pathway.rb
- app/models/user.rb
- app/models/user_challenge.rb
- app/models/user_pathway.rb
- db/migrate/20221101125809_dropchallenges_users.rb
- db/schema.rb
- db/seeds.rb
fix: removed challenges_users from schema.
feat: path challenges validated
feat: user pathway validated
feat: users validated
feat: pathway validated
feat: challenges validated
feat: user challenges validated
> completed validations with testing, further inspection needed [MP-32]

- app/models/user_challenge.rb
- app/models/user_pathway.rb
feat: managed top test and works.
fix: cleared completed from user_challenges
fix: cleared completed from user_pathway
> validations done and tested [MP-32]

- app/views/shared/_navbar.html.erb
Removed fixed class from navbar to stop it from overlappin page content
Added sign up href to log in button
Added log out link, adapted for Rails 7
> feat: added log out, log in buttons

- Gemfile
- Gemfile.lock
- app/controllers/path_challenges_controller.rb
- app/controllers/pathways_controller.rb
- app/models/challenge.rb
- app/models/path_challenge.rb
- app/models/pathway.rb
- app/views/pathways/_challenge.html.erb
- app/views/pathways/_form.html.erb
- app/views/pathways/_pathway.html.erb
- app/views/pathways/edit.html.erb
- app/views/pathways/index.html.erb
- app/views/pathways/new.html.erb
- app/views/pathways/show.html.erb
- config/initializers/simple_form.rb
- config/locales/simple_form.en.yml
- config/routes.rb
- db/seeds.rb
- Mentor can create | edit | destroy Pathway
- Modify pathway routes
- Added index | show | new | edit views
- Index page displays all pathway instances
- Show page displays a pathway and related challenges
- To do so, Added 'Pathway' and 'PathChallenge' seeds
- For new & edit, use 'Simple_form' and install it in Gemfile
> Pathway CRUD Action

- db/seeds.rb
fix: removed user_challenge loop
feat: updated seed file by resolving issues highlighted by team.
> resolved and updated seed file [MP-29]

- app/models/profile.rb
- app/models/user.rb
- config/database.yml
- db/schema.rb
- spec/factories/profiles.rb
- spec/models/profile_spec.rb
Written basic test for profile model
Test by running `bundle exec rspec spec/models`
Please give feedback!
> Mp 90 profile model

- app/controllers/user_pathways_controller.rb
- config/routes.rb
- db/migrate/20221117123147_add_approve_to_user_pathway.rb
- db/schema.rb
To allow a mentor to approve a sign-up:
* Add 'approved' field to user_pathway model => Everyone needs to `rails db:migrate` after they pull origin main
* Add 'approved' action to user_pathway controller
* Add 'approved' routes
We haven't figured out the routes for mentors and mentees and there is no view file yet, I just created the method.
Once we create views, we can use 'approved_path(@user_pathway)' to trigger the action.
> As a mentor I can approve a sign up to a pathway [MP-62]

- app/controllers/pathways_controller.rb
Fix an error when you create a pathway by assigning current_user as a pathway.user
> Add user_id to create pathways [MP-83]

- db/seeds.rb
Added 2 fresh users, without associations to seed! One mentor, one mentee
> feat: added 2 fresh users to seed

- app/controllers/profiles_controller.rb
- app/models/profile.rb
- app/views/profiles/edit.html.erb
- app/views/profiles/show.html.erb
- config/database.yml
- config/routes.rb
- spec/requests/profile_spec.rb
- Profile edit built into profile show page using [turbo frame](https://nts.strzibny.name/single-attribute-in-place-editing-turbo/)
- Only a profile owner can edit their profile
> Mp 87 as a user i can update my profile so that i can keep my public information up to date

- app/controllers/profiles_controller.rb
- app/controllers/user_pathways_controller.rb
- app/models/comment.rb
- app/models/pathway.rb
- app/models/user.rb
- app/models/user_pathway.rb
- app/views/profiles/show.html.erb
- app/views/user_pathways/show.html.erb
- config/routes.rb
- db/migrate/20221120201325_create_comments.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/comments.rb
- spec/models/comment_spec.rb
- Displaying user_pathways. 
- Routes for user_pathways.
> User pathways

- app/controllers/user_pathways_controller.rb
- app/models/user_pathway.rb
- app/views/pathways/show.html.erb
- app/views/user_pathways/signup.html.erb
- config/routes.rb
feat: updated user_pathway model.
feat: button allows you to sign up to pathway when you are logged in.
feat: button for mentee sign up only visible when mentee is logged in.
> Update signup button [MP-61]

- app/views/shared/_navbar.html.erb
feat: Added a nav bar button called sign up.
feat: sign up directs user to sign up page.
feat: button disappears once user has signed in.
feat: Once user signed in you can clearly see their name in navbar.
> added sign up button in navbar

- app/views/pathways/_pathway.html.erb
- app/views/pathways/index.html.erb
- db/schema.rb
Added flex grow on pathway details to ensure consistent card sizing when content length is different
> Basic grid styling on pathways index page

- app/controllers/user_challenges_controller.rb
- app/controllers/user_pathways_controller.rb
- app/models/challenge.rb
- app/models/user_challenge.rb
- app/models/user_pathway.rb
- app/views/challenges/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/pathways/_challenge.html.erb
- app/views/pathways/_pathway.html.erb
- app/views/pathways/show.html.erb
- app/views/profiles/show.html.erb
- app/views/shared/_footer.html.erb
- app/views/user_challenges/show.html.erb
- app/views/user_pathways/show.html.erb
- db/migrate/20221212130618_add_notes_to_user_challenges.rb
- db/migrate/20221212132900_add_user_pathway_to_user_challenges.rb
- db/schema.rb
- spec/factories/challenges.rb
- spec/models/user_pathway_spec.rb
- Added necessary associations, with dependent destroys, to match schema diagram
- Added migrations, to match schema diagram
- Wrote unit tests, basic validations on user_pathways model
- When creating a user_pathway, a callback creates the necessary user_challenges, based on the pathway challenges and user_pathway (With tests)
- Styled pathway index, pathway show, challenge show
- Styled profile show, user_pathway show, user_challenge show
- When user clicks on pathway they are signed up on from pathway index, they are redirected to their user_pathway show instead of pathway show
> Mp 98 as a user i can see challenges for each of my pathways

- app/controllers/challenges_controller.rb
- app/views/pathways/_challenge.html.erb
- app/views/pathways/show.html.erb
- user can only see details of the first challenge in pathway show page.
- user can not click on a challenge to see challenge show page.
- challenge controller actions are inaccessible to user
> Mp 110 taster journey

- app/views/shared/_navbar.html.erb
- config/tailwind.config.js
- spec/models/path_challenge_spec.rb
- spec/models/pathway_spec.rb
- spec/models/user_challenge_spec.rb
feat: user_challenge testing [MP-67]
feat: path_challenege testing [MP-67]
feat: challenge testing [MP-67]
feat: pathway testing [MP-67]
feat: profile testing [MP-67]
feat: user_pathway testing [MP-67]
feat: user testing [MP-67]
> all model testing complete [MP-67]

- Gemfile
- app/controllers/profiles_controller.rb
- app/controllers/user_challenges_controller.rb
- app/controllers/user_pathways_controller.rb
- app/models/challenge.rb
- app/models/pathway.rb
- app/models/profile.rb
- app/models/user.rb
- app/models/user_pathway.rb
- bin/bundle
- config/routes.rb
- db/seeds.rb
- spec/factories/profiles.rb
- spec/models/challenge_spec.rb
- spec/models/comment_spec.rb
- spec/models/path_challenge_spec.rb
- spec/models/pathway_spec.rb
- spec/models/profile_spec.rb
- spec/models/user_challenge_spec.rb
- spec/models/user_pathway_spec.rb
- spec/models/user_spec.rb
- spec/requests/pathway_spec.rb
- spec/requests/profile_spec.rb
- spec/support/chrome.rb
- spec/support/controller_macros.rb
- spec/support/devise.rb
- spec/system/users_spec.rb
run `rubocop` -a and `standardrb --fix` to better conventions as per our style guide
> fix: style improvements

- app/controllers/pathways_controller.rb
- app/views/pathways/index.html.erb
Add a search bar on the pathway#index page.
So far we can only search by titles, I didn't use pg gem.
Once we add tags, we should add pg gem for multisearch.
> feat: add search bar on pathway#index page [MP-119]

- bin/setup
small change, adding equivalent of rails db:reset to bin/setup which we can run in one line `bin/setup && bin/dev`
> feat: add bundle exec rails db:setup to bin/setup

- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- config/tailwind.config.js
fix/MP-115-navbar-changed-to-new-design
> Final nav design

- app/controllers/users/confirmations_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users/unlocks_controller.rb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/schema.rb
originally, page would break if user signed out on a user_challenge
> user redirected to root page on logout [MP-143] 

- package.json
Reverts Mentor-Pathway/mentor-platform#108
> Revert "fix: dependencies in package.json"

- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/layouts/application.html.erb
styled login/signup forms
kept form width at 100%, will change to 50% when we have an image to use, to match Figma
Log in with Github button has no logo, will change if adding font awesome
styled validation error messages
> Mp 129 style log in and sign up pages
